# Generated by Django 2.0.9 on 2019-01-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapps', '0004_auto_20190124_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailbox',
            name='attachment',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
